version: "3.7"

services:
  webserver:
    image: nginx:1.13-alpine
    container_name: webserver
    depends_on:
      - php-fpm
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8080"

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        www_data_uid: 1000
        www_data_gid: 1000
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    ports:
      - "35729:35729"